//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DODTM.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DODTM.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the application.
        /// </summary>
        internal static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a mask?.
        /// </summary>
        internal static string ApplyAMask {
            get {
                return ResourceManager.GetString("ApplyAMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Sergey Krainov.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of images.
        /// </summary>
        internal static string CountOfImages {
            get {
                return ResourceManager.GetString("CountOfImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter path to image.
        /// </summary>
        internal static string EnterPathToImage {
            get {
                return ResourceManager.GetString("EnterPathToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the processing algorithm.
        /// </summary>
        internal static string ErrorWithAlgorithm {
            get {
                return ResourceManager.GetString("ErrorWithAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not contain the required extension!.
        /// </summary>
        internal static string ErrorWithImageRequires {
            get {
                return ResourceManager.GetString("ErrorWithImageRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the folder is not specified!.
        /// </summary>
        internal static string ErrorWithPathFolder {
            get {
                return ResourceManager.GetString("ErrorWithPathFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the file is not specified!.
        /// </summary>
        internal static string ErrorWithPathToFile {
            get {
                return ResourceManager.GetString("ErrorWithPathToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI image.
        /// </summary>
        internal static string imgDPI {
            get {
                return ResourceManager.GetString("imgDPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height image.
        /// </summary>
        internal static string imgHeight {
            get {
                return ResourceManager.GetString("imgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width image.
        /// </summary>
        internal static string imgWidth {
            get {
                return ResourceManager.GetString("imgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image processing.
        /// </summary>
        internal static string NameProject {
            get {
                return ResourceManager.GetString("NameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image.
        /// </summary>
        internal static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed successfully and save in.
        /// </summary>
        internal static string SuccessWork {
            get {
                return ResourceManager.GetString("SuccessWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
