# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET MAUI MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI workload
      run: |
        dotnet workload install maccatalyst --ignore-failed-sources
        dotnet workload install maui --ignore-failed-sources
    - name: Restore Dependencies
      run: dotnet restore DODTM/DODTM.csproj
    - name: Build MAUI MacCatalyst
      run: dotnet build DODTM/DODTM.csproj -c Release -f net8.0-maccatalyst --no-restore
    - name: Upload MacCatalyst Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: macos-ci-build
        path: DODTM/bin/Release/net8.0-maccatalyst/**/*.app/
